import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navigation } from "@/components/navigation";
import Link from "next/link";
import { links, profiles } from "@/lib/constants";
import { NavigationLink } from "@/components/navigation-link";
import { NavigationContent } from "@/components/navigation-content";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body suppressHydrationWarning>
        <main vaul-drawer-wrapper="" className="min-h-screen">
          <div className="lg:flex">
            <Navigation>
              <NavigationContent />
            </Navigation>
            <div className="flex flex-1 bg-neutral-50">{children}</div>
          </div>
        </main>
      </body>
    </html>
  );
}
